-- one to one
CREATE TABLE a (id INTEGER PRIMARY KEY, b_id INTEGER REFERENCES b(id));
CREATE TABLE b (id INTEGER PRIMARY KEY, a_id INTEGER REFERENCES a(id));

-- one to many
CREATE TABLE c (id INTEGER PRIMARY KEY, d_id INTEGER REFERENCES d(id));
CREATE TABLE d (id INTEGER PRIMARY KEY);

-- many to one
CREATE TABLE e (id INTEGER PRIMARY KEY);
CREATE TABLE f (id INTEGER PRIMARY KEY, e_id INTEGER REFERENCES e(id));

-- many to many
CREATE TABLE g (id INTEGER PRIMARY KEY);
CREATE TABLE h (id INTEGER PRIMARY KEY);
CREATE TABLE g_h (g_id INTEGER REFERENCES g(id), h_id INTEGER REFERENCES h(id));
